# Generated by Django 2.2.1 on 2019-05-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='followed_by', to='twitterclone.TwitterUser'),
        ),
    ]
